
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.util.Hashtable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anton
 */
public class FacultyStaff extends javax.swing.JFrame {

    private Connection con;
    private boolean staffPermission = false;
    private boolean stuSearchAction = true;
    private boolean stuNewAction = true;
    private boolean facSearchAction = true;
    private boolean facNewAction = true;
    private boolean staSearchAction = true;
    private boolean staNewAction = true;
    private boolean depSearchAction = true;
    private boolean depNewAction = true;
    private boolean corSearchAction = true;
    private boolean corNewAction = true;
    private boolean enrlSearchAction = true;
    private boolean enrlNewAction = true;

    /**
     * Creates new form
     */
    public FacultyStaff(Connection passedcon) {
        setConnection(passedcon);
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        populateComboBoxes();
        disableNewButtons();
    }

    public FacultyStaff(Connection passedcon, boolean staffPermission) {
        setConnection(passedcon);
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        populateComboBoxes();
        setStaffPermission(staffPermission);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facstaffTab = new javax.swing.JTabbedPane();
        studentTab = new javax.swing.JPanel();
        stuIDLabel = new javax.swing.JLabel();
        stuID = new javax.swing.JTextField();
        stuNameLabel = new javax.swing.JLabel();
        stuName = new javax.swing.JTextField();
        stuMajorLabel = new javax.swing.JLabel();
        stuMajor = new javax.swing.JTextField();
        stuLevelLabel = new javax.swing.JLabel();
        stuLevel = new javax.swing.JComboBox();
        stuAgeLabel = new javax.swing.JLabel();
        stuAge = new javax.swing.JTextField();
        stuNew = new javax.swing.JButton();
        stuSearch = new javax.swing.JButton();
        stuClear = new javax.swing.JButton();
        stuScroll = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        facultyTab = new javax.swing.JPanel();
        facIDLabel = new javax.swing.JLabel();
        facID = new javax.swing.JTextField();
        facNameLabel = new javax.swing.JLabel();
        facName = new javax.swing.JTextField();
        facDepLabel = new javax.swing.JLabel();
        facDep = new javax.swing.JComboBox();
        facNew = new javax.swing.JButton();
        facSearch = new javax.swing.JButton();
        facClear = new javax.swing.JButton();
        facScroll = new javax.swing.JScrollPane();
        facTable = new javax.swing.JTable();
        staffTab = new javax.swing.JPanel();
        staIDLabel = new javax.swing.JLabel();
        staID = new javax.swing.JTextField();
        staNameLabel = new javax.swing.JLabel();
        staName = new javax.swing.JTextField();
        staDepLabel = new javax.swing.JLabel();
        staDep = new javax.swing.JComboBox();
        staNew = new javax.swing.JButton();
        staSearch = new javax.swing.JButton();
        staClear = new javax.swing.JButton();
        staScroll = new javax.swing.JScrollPane();
        staTable = new javax.swing.JTable();
        deptTab = new javax.swing.JPanel();
        depIDLabel = new javax.swing.JLabel();
        depID = new javax.swing.JTextField();
        depNameLabel = new javax.swing.JLabel();
        depName = new javax.swing.JTextField();
        depNew = new javax.swing.JButton();
        depSearch = new javax.swing.JButton();
        depClear = new javax.swing.JButton();
        depScroll = new javax.swing.JScrollPane();
        depTable = new javax.swing.JTable();
        courseTab = new javax.swing.JPanel();
        corIDLabel = new javax.swing.JLabel();
        corID = new javax.swing.JTextField();
        corNameLabel = new javax.swing.JLabel();
        corName = new javax.swing.JTextField();
        corTimeLabel = new javax.swing.JLabel();
        corTime = new javax.swing.JTextField();
        corRoomLabel = new javax.swing.JLabel();
        corRoom = new javax.swing.JTextField();
        corInstructorLabel = new javax.swing.JLabel();
        corInstructor = new javax.swing.JComboBox();
        corSizeLabel = new javax.swing.JLabel();
        corSize = new javax.swing.JTextField();
        corNew = new javax.swing.JButton();
        corSearch = new javax.swing.JButton();
        corClear = new javax.swing.JButton();
        corScroll = new javax.swing.JScrollPane();
        corTable = new javax.swing.JTable();
        enrlTab = new javax.swing.JPanel();
        enrlCourseLabel = new javax.swing.JLabel();
        enrlCourse = new javax.swing.JComboBox();
        enrlStudentLabel = new javax.swing.JLabel();
        enrlStudent = new javax.swing.JComboBox();
        enrlExam1Label = new javax.swing.JLabel();
        enrlExam1 = new javax.swing.JTextField();
        enrlExam2Label = new javax.swing.JLabel();
        enrlExam2 = new javax.swing.JTextField();
        enrlFinalLabel = new javax.swing.JLabel();
        enrlFinal = new javax.swing.JTextField();
        enrlNew = new javax.swing.JButton();
        enrlSearch = new javax.swing.JButton();
        enrlClear = new javax.swing.JButton();
        enrlScroll = new javax.swing.JScrollPane();
        enrlTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facstaffTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                facstaffTabStateChanged(evt);
            }
        });

        studentTab.setPreferredSize(new java.awt.Dimension(700, 500));

        stuIDLabel.setText("ID");

        stuNameLabel.setText("Name");

        stuMajorLabel.setText("Major");

        stuLevelLabel.setText("Level");

        stuLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","freshman", "sophomore", "junior", "senior", "master", "phd" }));

        stuAgeLabel.setText("Age");

        stuNew.setText("New");
        stuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuNewActionPerformed(evt);
            }
        });

        stuSearch.setText("Search");
        stuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuSearchActionPerformed(evt);
            }
        });

        stuClear.setText("Clear");
        stuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuClearActionPerformed(evt);
            }
        });

        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Major", "Level", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stuScroll.setViewportView(stuTable);

        javax.swing.GroupLayout studentTabLayout = new javax.swing.GroupLayout(studentTab);
        studentTab.setLayout(studentTabLayout);
        studentTabLayout.setHorizontalGroup(
            studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stuScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(studentTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(studentTabLayout.createSequentialGroup()
                                .addComponent(stuNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stuSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stuClear))
                        .addGroup(studentTabLayout.createSequentialGroup()
                                .addComponent(stuAgeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stuAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(studentTabLayout.createSequentialGroup()
                                .addComponent(stuIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stuID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(studentTabLayout.createSequentialGroup()
                                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stuNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(stuMajorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(stuLevelLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stuMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentTabLayout.setVerticalGroup(
            studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stuIDLabel)
                        .addComponent(stuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stuNameLabel)
                        .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stuMajorLabel)
                        .addComponent(stuMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stuLevelLabel)
                        .addComponent(stuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stuAgeLabel)
                        .addComponent(stuAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stuClear)
                        .addComponent(stuSearch)
                        .addComponent(stuNew))
                .addGap(18, 18, 18)
                .addComponent(stuScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Students", studentTab);

        facultyTab.setPreferredSize(new java.awt.Dimension(700, 50));

        facIDLabel.setText("ID");

        facNameLabel.setText("Name");

        facDepLabel.setText("Department");

        facDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        facNew.setText("New");
        facNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facNewActionPerformed(evt);
            }
        });

        facSearch.setText("Search");
        facSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facSearchActionPerformed(evt);
            }
        });

        facClear.setText("Clear");
        facClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facClearActionPerformed(evt);
            }
        });

        facTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facScroll.setViewportView(facTable);

        javax.swing.GroupLayout facultyTabLayout = new javax.swing.GroupLayout(facultyTab);
        facultyTab.setLayout(facultyTabLayout);
        facultyTabLayout.setHorizontalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(facultyTabLayout.createSequentialGroup()
                                .addComponent(facNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facClear))
                        .addGroup(facultyTabLayout.createSequentialGroup()
                                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(facNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(facDepLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(facName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(facDep, 0, 200, Short.MAX_VALUE)))
                        .addGroup(facultyTabLayout.createSequentialGroup()
                                .addComponent(facIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        facultyTabLayout.setVerticalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facIDLabel)
                        .addComponent(facID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facNameLabel)
                        .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(facDepLabel))
                .addGap(18, 18, 18)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facClear)
                        .addComponent(facSearch)
                        .addComponent(facNew))
                .addGap(18, 18, 18)
                .addComponent(facScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Faculty", facultyTab);

        staffTab.setPreferredSize(new java.awt.Dimension(700, 500));

        staIDLabel.setText("ID");

        staNameLabel.setText("Name");

        staDepLabel.setText("Department");

        staDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        staNew.setText("New");
        staNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staNewActionPerformed(evt);
            }
        });

        staSearch.setText("Search");
        staSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staSearchActionPerformed(evt);
            }
        });

        staClear.setText("Clear");
        staClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staClearActionPerformed(evt);
            }
        });

        staTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staScroll.setViewportView(staTable);

        javax.swing.GroupLayout staffTabLayout = new javax.swing.GroupLayout(staffTab);
        staffTab.setLayout(staffTabLayout);
        staffTabLayout.setHorizontalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(staffTabLayout.createSequentialGroup()
                                .addComponent(staNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staClear))
                        .addGroup(staffTabLayout.createSequentialGroup()
                                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(staNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(staDepLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(staName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(staDep, 0, 200, Short.MAX_VALUE)))
                        .addGroup(staffTabLayout.createSequentialGroup()
                                .addComponent(staIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffTabLayout.setVerticalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(staIDLabel)
                        .addComponent(staID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(staNameLabel)
                        .addComponent(staName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(staDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(staDepLabel))
                .addGap(18, 18, 18)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(staClear)
                        .addComponent(staSearch)
                        .addComponent(staNew))
                .addGap(18, 18, 18)
                .addComponent(staScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Staff", staffTab);

        deptTab.setPreferredSize(new java.awt.Dimension(700, 500));

        depIDLabel.setText("ID");

        depNameLabel.setText("Name");

        depNew.setText("New");
        depNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNewActionPerformed(evt);
            }
        });

        depSearch.setText("Search");
        depSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depSearchActionPerformed(evt);
            }
        });

        depClear.setText("Clear");
        depClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depClearActionPerformed(evt);
            }
        });

        depTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        depScroll.setViewportView(depTable);

        javax.swing.GroupLayout deptTabLayout = new javax.swing.GroupLayout(deptTab);
        deptTab.setLayout(deptTabLayout);
        deptTabLayout.setHorizontalGroup(
            deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(deptTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(deptTabLayout.createSequentialGroup()
                                .addComponent(depIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(deptTabLayout.createSequentialGroup()
                                .addComponent(depNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(deptTabLayout.createSequentialGroup()
                                .addComponent(depNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deptTabLayout.setVerticalGroup(
            deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depIDLabel)
                        .addComponent(depID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depNameLabel)
                        .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depSearch)
                        .addComponent(depClear)
                        .addComponent(depNew))
                .addGap(18, 18, 18)
                .addComponent(depScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Departments", deptTab);

        courseTab.setPreferredSize(new java.awt.Dimension(700, 500));

        corIDLabel.setText("ID");

        corNameLabel.setText("Name");

        corTimeLabel.setText("Time");

        corRoomLabel.setText("Location");

        corInstructorLabel.setText("Instructor");

        corInstructor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        corSizeLabel.setText("Size Limit");

        corNew.setText("New");
        corNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corNewActionPerformed(evt);
            }
        });

        corSearch.setText("Search");
        corSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corSearchActionPerformed(evt);
            }
        });

        corClear.setText("Clear");
        corClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corClearActionPerformed(evt);
            }
        });

        corTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Time", "Location", "Instructor", "Size Limit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        corScroll.setViewportView(corTable);

        javax.swing.GroupLayout courseTabLayout = new javax.swing.GroupLayout(courseTab);
        courseTab.setLayout(courseTabLayout);
        courseTabLayout.setHorizontalGroup(
            courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(courseTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corRoomLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corInstructorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corSizeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corSize, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                                .addComponent(corNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        courseTabLayout.setVerticalGroup(
            courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corIDLabel)
                        .addComponent(corID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corNameLabel)
                        .addComponent(corName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corTimeLabel)
                        .addComponent(corTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corRoomLabel)
                        .addComponent(corRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corInstructorLabel)
                        .addComponent(corInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corSizeLabel)
                        .addComponent(corSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(corClear)
                        .addComponent(corSearch)
                        .addComponent(corNew))
                .addGap(18, 18, 18)
                .addComponent(corScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Courses", courseTab);

        enrlTab.setPreferredSize(new java.awt.Dimension(700, 500));

        enrlCourseLabel.setText("Course");

        enrlCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        enrlStudentLabel.setText("Student");

        enrlStudent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        enrlExam1Label.setText("Exam 1");

        enrlExam2Label.setText("Exam 2");

        enrlFinalLabel.setText("Final");

        enrlNew.setText("New");
        enrlNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrlNewActionPerformed(evt);
            }
        });

        enrlSearch.setText("Search");
        enrlSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrlSearchActionPerformed(evt);
            }
        });

        enrlClear.setText("Clear");
        enrlClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrlClearActionPerformed(evt);
            }
        });

        enrlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Student", "Exam 1", "Exam 2", "Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrlScroll.setViewportView(enrlTable);

        javax.swing.GroupLayout enrlTabLayout = new javax.swing.GroupLayout(enrlTab);
        enrlTab.setLayout(enrlTabLayout);
        enrlTabLayout.setHorizontalGroup(
            enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrlTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enrlTabLayout.createSequentialGroup()
                        .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enrlCourseLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlStudentLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlFinalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlExam1Label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlExam2Label, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enrlFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(enrlExam2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(enrlExam1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(enrlCourse, 0, 200, Short.MAX_VALUE)
                            .addComponent(enrlStudent, 0, 200, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enrlTabLayout.createSequentialGroup()
                        .addComponent(enrlNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enrlSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enrlClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(enrlScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        enrlTabLayout.setVerticalGroup(
            enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrlTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlCourseLabel)
                    .addComponent(enrlCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlStudentLabel)
                    .addComponent(enrlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlExam1Label)
                    .addComponent(enrlExam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlExam2Label)
                    .addComponent(enrlExam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlFinalLabel)
                    .addComponent(enrlFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlSearch)
                    .addComponent(enrlClear)
                    .addComponent(enrlNew))
                .addGap(18, 18, 18)
                .addComponent(enrlScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Enrollment", enrlTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(facstaffTab)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(facstaffTab)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // table select action listeners
    private void addStuTableListener() {
        stuTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        stuTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    Integer selectedRow = lsm.getMinSelectionIndex();
                    Integer numcols = stuTable.getColumnCount();
                    Hashtable<String,Object> colhash = new Hashtable<String, Object>();
                    for (int col=0; col < numcols; col++) {
                        String colname = stuTable.getColumnName(col);
                        Object colcontent = stuTable.getValueAt(selectedRow,col);
                        if (colcontent != null) {
                            colhash.put(colname, colcontent);
                        }
                    }
                    // id should never be null
                    stuID.setText(colhash.get("ID").toString());
                    stuID.setEnabled(false);
                    // name should never be null
                    stuName.setText(colhash.get("Name").toString());
                    if (colhash.get("Major") != null) {
                        stuMajor.setText(colhash.get("Major").toString());
                    }
                    else {
                        stuMajor.setText("");
                    }
                    stuLevel.setSelectedItem(colhash.get("Level"));
                    if (colhash.get("Age") != null) {
                        stuAge.setText(colhash.get("Age").toString());
                    }
                    else {
                        stuAge.setText("");
                    }
                    stuNew.setText("Delete");
                    stuNewAction = false;
                    stuSearch.setText("Edit");
                    stuSearchAction = false;
                }
            }
        });
    }

    private void addFacTableListener() {
        facTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        facTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    Integer selectedRow = lsm.getMinSelectionIndex();
                    Integer numcols = facTable.getColumnCount();
                    Hashtable<String,Object> colhash = new Hashtable<String, Object>();
                    for (int col=0; col < numcols; col++) {
                        String colname = facTable.getColumnName(col);
                        Object colcontent = facTable.getValueAt(selectedRow,col);
                        if (colcontent != null) {
                            colhash.put(colname, colcontent);
                        }
                    }
                    // id should never be null
                    facID.setText(colhash.get("ID").toString());
                    facID.setEnabled(false);
                    // name should never be null
                    facName.setText(colhash.get("Name").toString());
                    // department should never be null
                    facDep.setSelectedItem(colhash.get("Department").toString());
                    facNew.setText("Delete");
                    facNewAction = false;
                    facSearch.setText("Edit");
                    facSearchAction = false;
                }
            }
        });
    }

    private void addStaTableListener() {
        staTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        staTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    Integer selectedRow = lsm.getMinSelectionIndex();
                    Integer numcols = staTable.getColumnCount();
                    Hashtable<String,Object> colhash = new Hashtable<String, Object>();
                    for (int col=0; col < numcols; col++) {
                        String colname = staTable.getColumnName(col);
                        Object colcontent = staTable.getValueAt(selectedRow,col);
                        if (colcontent != null) {
                            colhash.put(colname, colcontent);
                        }
                    }
                    // id should never be null
                    staID.setText(colhash.get("ID").toString());
                    staID.setEnabled(false);
                    // name should never be null
                    staName.setText(colhash.get("Name").toString());
                    // department should never be null
                    staDep.setSelectedItem(colhash.get("Department").toString());
                    staNew.setText("Delete");
                    staNewAction = false;
                    staSearch.setText("Edit");
                    staSearchAction = false;
                }
            }
        });
    }

    private void addDepTableListener() {
        depTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        depTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    Integer selectedRow = lsm.getMinSelectionIndex();
                    Integer numcols = depTable.getColumnCount();
                    Hashtable<String,Object> colhash = new Hashtable<String, Object>();
                    for (int col=0; col < numcols; col++) {
                        String colname = depTable.getColumnName(col);
                        Object colcontent = depTable.getValueAt(selectedRow,col);
                        if (colcontent != null) {
                            colhash.put(colname, colcontent);
                        }
                    }
                    // id should never be null
                    depID.setText(colhash.get("ID").toString());
                    depID.setEnabled(false);
                    // name should never be null
                    depName.setText(colhash.get("Name").toString());
                    depNew.setText("Delete");
                    depNewAction = false;
                    depSearch.setText("Edit");
                    depSearchAction = false;
                }
            }
        });
    }

    private void addCorTableListener() {
        corTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        corTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    Integer selectedRow = lsm.getMinSelectionIndex();
                    Integer numcols = corTable.getColumnCount();
                    Hashtable<String,Object> colhash = new Hashtable<String, Object>();
                    for (int col=0; col < numcols; col++) {
                        String colname = corTable.getColumnName(col);
                        Object colcontent = corTable.getValueAt(selectedRow,col);
                        if (colcontent != null) {
                            colhash.put(colname, colcontent);
                        }
                    }
                    // id should never be null
                    corID.setText(colhash.get("ID").toString());
                    corID.setEnabled(false);
                    if (colhash.get("Name") != null) {
                        corName.setText(colhash.get("Name").toString());
                    }
                    else {
                        corName.setText("");
                    }
                    if (colhash.get("Time") != null) {
                        corTime.setText(colhash.get("Time").toString());
                    }
                    else {
                        corTime.setText("");
                    }
                    if (colhash.get("Location") != null) {
                        corRoom.setText(colhash.get("Location").toString());
                    }
                    else {
                        corRoom.setText("");
                    }
                    // instructor should never be null
                    corInstructor.setSelectedItem(colhash.get("Instructor").toString());
                    if (colhash.get("Size Limit") != null) {
                        corSize.setText(colhash.get("Size Limit").toString());
                    }
                    else {
                        corSize.setText("0");
                    }
                    corNew.setText("Delete");
                    corNewAction = false;
                    corSearch.setText("Edit");
                    corSearchAction = false;
                }
            }
        });
    }

    private void addEnrlTableListener() {
        enrlTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        enrlTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) return;
                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    Integer selectedRow = lsm.getMinSelectionIndex();
                    Integer numcols = enrlTable.getColumnCount();
                    Hashtable<String,Object> colhash = new Hashtable<String, Object>();
                    for (int col=0; col < numcols; col++) {
                        String colname = enrlTable.getColumnName(col);
                        Object colcontent = enrlTable.getValueAt(selectedRow,col);
                        if (colcontent != null) {
                            colhash.put(colname, colcontent);
                        }
                    }
                    // course should never be null
                    enrlCourse.setSelectedItem(colhash.get("Course").toString());
                    enrlCourse.setEnabled(false);
                    // student should never be null
                    enrlStudent.setSelectedItem(colhash.get("Student").toString());
                    enrlStudent.setEnabled(false);
                    if (colhash.get("Exam 1") != null) {
                        enrlExam1.setText(colhash.get("Exam 1").toString());
                    }
                    else {
                        enrlExam1.setText("");
                    }
                    if (colhash.get("Exam 2") != null) {
                        enrlExam2.setText(colhash.get("Exam 2").toString());
                    }
                    else {
                        enrlExam2.setText("");
                    }
                    if (colhash.get("Final") != null) {
                        enrlFinal.setText(colhash.get("Final").toString());
                    }
                    else {
                        enrlFinal.setText("");
                    }
                    enrlNew.setText("Delete");
                    enrlNewAction = false;
                    enrlSearch.setText("Edit");
                    enrlSearchAction = false;
                }
            }
        });
    }


    private void disableNewButtons() {
        stuNew.setVisible(false);
        corNew.setVisible(false);
        depNew.setVisible(false);
        enrlNew.setVisible(false);
        facNew.setVisible(false);
        staNew.setVisible(false);
        this.revalidate();
        this.repaint();
    }

    @SuppressWarnings("unchecked")
    private void populateComboBoxes() {
        Database db = new Database();
        Object[] deps = db.getDepList(con);
        for (Object dep : deps) {
            facDep.addItem(dep);
            staDep.addItem(dep);
        }
        Object[] facs = db.getFacList(con);
        for (Object fac : facs) {
            corInstructor.addItem(fac);
        }
        Object[] stus = db.getStuList(con);
        for (Object stu : stus) {
            enrlStudent.addItem(stu);
        }
        Object[] cors = db.getCorList(con);
        for (Object cor : cors) {
            enrlCourse.addItem(cor);
        }
    }

    private void clearComboBoxes() {
        while (facDep.getItemCount() > 1) {
            facDep.removeItemAt(1);
        }
        while (staDep.getItemCount() > 1) {
            staDep.removeItemAt(1);
        }
        while (corInstructor.getItemCount() > 1) {
            corInstructor.removeItemAt(1);
        }
        while (enrlCourse.getItemCount() > 1) {
            enrlCourse.removeItemAt(1);
        }
        while (enrlStudent.getItemCount() > 1) {
            enrlStudent.removeItemAt(1);
        }
    }

    // student buttons
    private void stuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuNewActionPerformed
        Database db = new Database();
        Integer sid = -1;
        String sname = "-1";
        String major = "-1";
        String s_level = "-1";
        Integer age = -1;
        if (!stuID.getText().isEmpty()) {
            sid = Integer.parseInt(stuID.getText());
        }
        if (!stuName.getText().isEmpty()) {
            sname = stuName.getText();
        }
        if (!stuMajor.getText().isEmpty()) {
            major = stuMajor.getText();
        }
        if (!String.valueOf(stuLevel.getSelectedItem()).isEmpty()) {
            s_level = String.valueOf(stuLevel.getSelectedItem()).toLowerCase();
        }
        if (!stuAge.getText().isEmpty()) {
            age = Integer.parseInt(stuAge.getText());
        }
        // do new action
        if (stuNewAction && staffPermission) {
            db.newStu(con, sid, sname, major, s_level, age);
            clearStuForm();
            stuID.setEnabled(true);
            stuNew.setText("New");
            stuNewAction = true;
            stuSearch.setText("Search");
            stuSearchAction = true;
            Object[][] allstu = db.searchStu(con);
            cleartable(stuTable);
            addtoTable(stuTable,allstu);
        }
        // do delete action
        else if (!stuNewAction && staffPermission){
            db.delStu(con, sid);
            clearStuForm();
            stuID.setEnabled(true);
            stuNew.setText("New");
            stuNewAction = true;
            stuSearch.setText("Search");
            stuSearchAction = true;
            Object[][] allstu = db.searchStu(con);
            cleartable(stuTable);
            addtoTable(stuTable,allstu);
        }
    }//GEN-LAST:event_stuNewActionPerformed

    private void stuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuSearchActionPerformed
        Database db = new Database();
        Integer sid = -1;
        String sname = "-1";
        String major = "-1";
        String s_level = "-1";
        Integer age = -1;
        if (!stuID.getText().isEmpty()) {
            sid = Integer.parseInt(stuID.getText());
        }
        if (!stuName.getText().isEmpty()) {
            sname = stuName.getText();
        }
        if (!stuMajor.getText().isEmpty()) {
            major = stuMajor.getText();
        }
        if (!String.valueOf(stuLevel.getSelectedItem()).isEmpty()) {
            s_level = String.valueOf(stuLevel.getSelectedItem()).toLowerCase();
        }
        if (!stuAge.getText().isEmpty()) {
            age = Integer.parseInt(stuAge.getText());
        }
        // do search action
        if (stuSearchAction) {
            Object[][] result = db.searchStu(con, sid, sname, major, s_level, age);
            cleartable(stuTable);
            addtoTable(stuTable, result);
        }
        // do edit action
        else if (!stuSearchAction && staffPermission){
            db.editStu(con, sid, sname, major, s_level, age);
            clearStuForm();
            stuID.setEnabled(true);
            stuNew.setText("New");
            stuNewAction = true;
            stuSearch.setText("Search");
            stuSearchAction = true;
            Object[][] allstu = db.searchStu(con);
            cleartable(stuTable);
            addtoTable(stuTable,allstu);
        }
    }//GEN-LAST:event_stuSearchActionPerformed

    private void stuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuClearActionPerformed
        cleartable(stuTable);
        clearStuForm();
        stuID.setEnabled(true);
        stuNew.setText("New");
        stuNewAction = true;
        stuSearch.setText("Search");
        stuSearchAction = true;
        Database db = new Database();
        Object[][] allstu = db.searchStu(con);
        addtoTable(stuTable,allstu);
    }//GEN-LAST:event_stuClearActionPerformed

    // faculty buttons
    private void facNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facNewActionPerformed
        Database db = new Database();
        Integer fid = -1;
        String fname = "-1";
        String dname = "-1";
        if (!facID.getText().isEmpty()) {
            fid = Integer.parseInt(facID.getText());
        }
        if (!facName.getText().isEmpty()) {
            fname = facName.getText();
        }
        if (!facDep.getSelectedItem().toString().isEmpty()) {
            dname = facDep.getSelectedItem().toString();
        }
        // do new action
        if (facNewAction && staffPermission) {
            db.newFac(con, fid, fname, dname);
            clearFacForm();
            facID.setEnabled(true);
            facNew.setText("New");
            facNewAction = true;
            facSearch.setText("Search");
            facSearchAction = true;
            Object[][] allfac = db.searchFac(con);
            cleartable(facTable);
            addtoTable(facTable,allfac);
            // clear and repopulate combo boxes with new faculty list
            clearComboBoxes();
            populateComboBoxes();
        }
        // do delete action
        else if (!facNewAction && staffPermission){
            db.delFac(con, fid);
            clearFacForm();
            facID.setEnabled(true);
            facNew.setText("New");
            facNewAction = true;
            facSearch.setText("Search");
            facSearchAction = true;
            Object[][] allfac = db.searchFac(con);
            cleartable(facTable);
            addtoTable(facTable,allfac);
            // clear and repopulate combo boxes with new faculty list
            clearComboBoxes();
            populateComboBoxes();
        }
    }//GEN-LAST:event_facNewActionPerformed

    private void facSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facSearchActionPerformed
        Database db = new Database();
        Integer fid = -1;
        String fname = "-1";
        String dname = "-1";
        if (!facID.getText().isEmpty()) {
            fid = Integer.parseInt(facID.getText());
        }
        if (!facName.getText().isEmpty()) {
            fname = facName.getText();
        }
        if (!facDep.getSelectedItem().toString().isEmpty()) {
            dname = facDep.getSelectedItem().toString();
        }
        // do search action
        if (facSearchAction) {
            Object[][] result = db.searchFac(con, fid, fname, dname);
            cleartable(facTable);
            addtoTable(facTable, result);
        }
        // do edit action
        else if (!facSearchAction && staffPermission){
            db.editFac(con, fid, fname, dname);
            clearFacForm();
            facID.setEnabled(true);
            facNew.setText("New");
            facNewAction = true;
            facSearch.setText("Search");
            facSearchAction = true;
            Object[][] allfac = db.searchFac(con);
            cleartable(facTable);
            addtoTable(facTable,allfac);
            // clear and repopulate combo boxes with new faculty list
            clearComboBoxes();
            populateComboBoxes();
        }
    }//GEN-LAST:event_facSearchActionPerformed

    private void facClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facClearActionPerformed
        cleartable(facTable);
        clearFacForm();
        facID.setEnabled(true);
        facNew.setText("New");
        facNewAction = true;
        facSearch.setText("Search");
        facSearchAction = true;
        Database db = new Database();
        Object[][] allfac = db.searchFac(con);
        addtoTable(facTable,allfac);
    }//GEN-LAST:event_facClearActionPerformed

    // staff buttons
    private void staNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staNewActionPerformed
        Database db = new Database();
        Integer sid = -1;
        String sname = "-1";
        String dname = "-1";
        if (!staID.getText().isEmpty()) {
            sid = Integer.parseInt(staID.getText());
        }
        if (!staName.getText().isEmpty()) {
            sname = staName.getText();
        }
        if (!staDep.getSelectedItem().toString().isEmpty()) {
            dname = staDep.getSelectedItem().toString();
        }
        // do new action
        if (staNewAction && staffPermission) {
            db.newSta(con, sid, sname, dname);
            clearStaForm();
            staID.setEnabled(true);
            staNew.setText("New");
            staNewAction = true;
            staSearch.setText("Search");
            staSearchAction = true;
            Object[][] allsta = db.searchSta(con);
            cleartable(staTable);
            addtoTable(staTable,allsta);
        }
        // do delete action
        else if (!staNewAction && staffPermission){
            db.delSta(con, sid);
            clearStaForm();
            staID.setEnabled(true);
            staNew.setText("New");
            staNewAction = true;
            staSearch.setText("Search");
            staSearchAction = true;
            Object[][] allsta = db.searchSta(con);
            cleartable(staTable);
            addtoTable(staTable,allsta);
        }
    }//GEN-LAST:event_staNewActionPerformed

    private void staSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staSearchActionPerformed
        Database db = new Database();
        Integer sid = -1;
        String sname = "-1";
        String dname = "-1";
        if (!staID.getText().isEmpty()) {
            sid = Integer.parseInt(staID.getText());
        }
        if (!staName.getText().isEmpty()) {
            sname = staName.getText();
        }
        if (!staDep.getSelectedItem().toString().isEmpty()) {
            dname = staDep.getSelectedItem().toString();
        }
        // do search action
        if (staSearchAction) {
            Object[][] result = db.searchSta(con, sid, sname, dname);
            cleartable(staTable);
            addtoTable(staTable, result);
        }
        // do edit action
        else if (!staSearchAction && staffPermission){
            db.editSta(con, sid, sname, dname);
            clearStaForm();
            staID.setEnabled(true);
            staNew.setText("New");
            staNewAction = true;
            staSearch.setText("Search");
            staSearchAction = true;
            Object[][] allsta = db.searchSta(con);
            cleartable(staTable);
            addtoTable(staTable,allsta);
        }
    }//GEN-LAST:event_staSearchActionPerformed

    private void staClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staClearActionPerformed
        cleartable(staTable);
        clearStaForm();
        staID.setEnabled(true);
        staNew.setText("New");
        staNewAction = true;
        staSearch.setText("Search");
        staSearchAction = true;
        Database db = new Database();
        Object[][] allsta = db.searchSta(con);
        addtoTable(staTable,allsta);
    }//GEN-LAST:event_staClearActionPerformed

    // department buttons
    private void depNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNewActionPerformed
        Database db = new Database();
        Integer did = -1;
        String dname = "-1";
        if (!depID.getText().isEmpty()) {
            did = Integer.parseInt(depID.getText());
        }
        if (!depName.getText().isEmpty()) {
            dname = depName.getText();
        }
        // do new action
        if (depNewAction && staffPermission) {
            db.newDep(con, did, dname);
            clearDepForm();
            depID.setEnabled(true);
            depNew.setText("New");
            depNewAction = true;
            depSearch.setText("Search");
            depSearchAction = true;
            Object[][] alldep = db.searchDep(con);
            cleartable(depTable);
            addtoTable(depTable,alldep);
            // clear and repopulate combo boxes with new department list
            clearComboBoxes();
            populateComboBoxes();
        }
        // do delete action
        else if (!depNewAction && staffPermission){
            db.delDep(con, did);
            clearDepForm();
            depID.setEnabled(true);
            depNew.setText("New");
            depNewAction = true;
            depSearch.setText("Search");
            depSearchAction = true;
            Object[][] alldep = db.searchDep(con);
            cleartable(depTable);
            addtoTable(depTable,alldep);
            // clear and repopulate combo boxes with new department list
            clearComboBoxes();
            populateComboBoxes();
        }
    }//GEN-LAST:event_depNewActionPerformed

    private void depSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depSearchActionPerformed
        Database db = new Database();
        Integer did = -1;
        String dname = "-1";
        if (!depID.getText().isEmpty()) {
            did = Integer.parseInt(depID.getText());
        }
        if (!depName.getText().isEmpty()) {
            dname = depName.getText();
        }
        // do search action
        if (depSearchAction) {
            Object[][] result = db.searchDep(con, did, dname);
            cleartable(depTable);
            addtoTable(depTable, result);
        }
        // do edit action
        else if (!depSearchAction && staffPermission){
            db.editDep(con, did, dname);
            clearDepForm();
            depID.setEnabled(true);
            depNew.setText("New");
            depNewAction = true;
            depSearch.setText("Search");
            depSearchAction = true;
            Object[][] alldep = db.searchDep(con);
            cleartable(depTable);
            addtoTable(depTable,alldep);
            // clear and repopulate combo boxes with new department list
            clearComboBoxes();
            populateComboBoxes();
        }
    }//GEN-LAST:event_depSearchActionPerformed

    private void depClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depClearActionPerformed
        cleartable(depTable);
        clearDepForm();
        depID.setEnabled(true);
        depNew.setText("New");
        depNewAction = true;
        depSearch.setText("Search");
        depSearchAction = true;
        Database db = new Database();
        Object[][] alldep = db.searchDep(con);
        addtoTable(depTable,alldep);
    }//GEN-LAST:event_depClearActionPerformed

    // courses buttons
    private void corNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corNewActionPerformed
        Database db = new Database();
        String cid = "-1";
        String cname = "-1";
        String meets_at = "-1";
        String room = "-1";
        String fname = "-1";
        Integer limit = -1;
        if (!corID.getText().isEmpty()) {
            cid = corID.getText();
        }
        if (!corName.getText().isEmpty()) {
            cname = corName.getText();
        }
        if (!corTime.getText().isEmpty()) {
            meets_at = corTime.getText();
        }
        if (!corRoom.getText().isEmpty()) {
            room = corRoom.getText();
        }
        if (!corInstructor.getSelectedItem().toString().isEmpty()) {
            fname = corInstructor.getSelectedItem().toString();
        }
        if (!corSize.getText().isEmpty()) {
            limit = Integer.parseInt(corSize.getText());
        }
        // do new action
        if (corNewAction && staffPermission) {
            db.newCor(con, cid, cname, meets_at, room, fname, limit);
            clearCorForm();
            corID.setEnabled(true);
            corNew.setText("New");
            corNewAction = true;
            corSearch.setText("Search");
            corSearchAction = true;
            Object[][] allcor = db.searchCor(con);
            cleartable(corTable);
            addtoTable(corTable,allcor);
        }
        // do delete action
        else if (!corNewAction && staffPermission){
            db.delCor(con, cid);
            clearCorForm();
            corID.setEnabled(true);
            corNew.setText("New");
            corNewAction = true;
            corSearch.setText("Search");
            corSearchAction = true;
            Object[][] allcor = db.searchCor(con);
            cleartable(corTable);
            addtoTable(corTable,allcor);
        }
    }//GEN-LAST:event_corNewActionPerformed

    private void corSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corSearchActionPerformed
        Database db = new Database();
        String cid = "-1";
        String cname = "-1";
        String meets_at = "-1";
        String room = "-1";
        String fname = "-1";
        Integer limit = -1;
        if (!corID.getText().isEmpty()) {
            cid = corID.getText();
        }
        if (!corName.getText().isEmpty()) {
            cname = corName.getText();
        }
        if (!corTime.getText().isEmpty()) {
            meets_at = corTime.getText();
        }
        if (!corRoom.getText().isEmpty()) {
            room = corRoom.getText();
        }
        if (!corInstructor.getSelectedItem().toString().isEmpty()) {
            fname = corInstructor.getSelectedItem().toString();
        }
        if (!corSize.getText().isEmpty()) {
            limit = Integer.parseInt(corSize.getText());
        }
        // do search action
        if (corSearchAction) {
            Object[][] result = db.searchCor(con, cid, cname, meets_at, room, fname, limit);
            cleartable(corTable);
            addtoTable(corTable, result);
        }
        // do edit action
        else if (!corSearchAction && staffPermission){
            db.editCor(con, cid, cname, meets_at, room, fname, limit);
            clearCorForm();
            corID.setEnabled(true);
            corNew.setText("New");
            corNewAction = true;
            corSearch.setText("Search");
            corSearchAction = true;
            Object[][] allcor = db.searchCor(con);
            cleartable(corTable);
            addtoTable(corTable,allcor);
        }
    }//GEN-LAST:event_corSearchActionPerformed

    private void corClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corClearActionPerformed
        cleartable(corTable);
        clearCorForm();
        corID.setEnabled(true);
        corNew.setText("New");
        corNewAction = true;
        corSearch.setText("Search");
        corSearchAction = true;
        Database db = new Database();
        Object[][] allcor = db.searchCor(con);
        addtoTable(corTable,allcor);
    }//GEN-LAST:event_corClearActionPerformed

    // enrolled buttons
    private void enrlNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrlNewActionPerformed
        Database db = new Database();
        String cid = "-1";
        String sname = "-1";
        Integer exam1 = -1;
        Integer exam2 = -1;
        Integer finalg = -1;
        if (!enrlCourse.getSelectedItem().toString().isEmpty()) {
            cid = enrlCourse.getSelectedItem().toString();
        }
        if (!enrlStudent.getSelectedItem().toString().isEmpty()) {
            sname = enrlStudent.getSelectedItem().toString();
        }
        if (!enrlExam1.getText().isEmpty()) {
            exam1 = Integer.parseInt(enrlExam1.getText());
        }
        if (!enrlExam2.getText().isEmpty()) {
            exam2 = Integer.parseInt(enrlExam2.getText());
        }
        if (!enrlFinal.getText().isEmpty()) {
            finalg = Integer.parseInt(enrlFinal.getText());
        }
        // do new action
        if (enrlNewAction && staffPermission) {
            db.newEnrl(con, cid, sname, exam1, exam2, finalg);
            clearEnrlForm();
            enrlNew.setText("New");
            enrlNewAction = true;
            enrlSearch.setText("Search");
            enrlSearchAction = true;
            Object[][] allenrl = db.searchEnrl(con);
            cleartable(enrlTable);
            addtoTable(enrlTable,allenrl);
        }
        // do delete action
        else if (!enrlNewAction && staffPermission){
            db.delEnrl(con, cid, sname);
            clearEnrlForm();
            enrlCourse.setEnabled(true);
            enrlStudent.setEnabled(true);
            enrlNew.setText("New");
            enrlNewAction = true;
            enrlSearch.setText("Search");
            enrlSearchAction = true;
            Object[][] allenrl = db.searchEnrl(con);
            cleartable(enrlTable);
            addtoTable(enrlTable,allenrl);
        }
    }//GEN-LAST:event_enrlNewActionPerformed

    private void enrlSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrlSearchActionPerformed
        Database db = new Database();
        String cid = "-1";
        String sname = "-1";
        Integer exam1 = -1;
        Integer exam2 = -1;
        Integer finalg = -1;
        if (!enrlCourse.getSelectedItem().toString().isEmpty()) {
            cid = enrlCourse.getSelectedItem().toString();
        }
        if (!enrlStudent.getSelectedItem().toString().isEmpty()) {
            sname = enrlStudent.getSelectedItem().toString();
        }
        if (!enrlExam1.getText().isEmpty()) {
            exam1 = Integer.parseInt(enrlExam1.getText());
        }
        if (!enrlExam2.getText().isEmpty()) {
            exam2 = Integer.parseInt(enrlExam2.getText());
        }
        if (!enrlFinal.getText().isEmpty()) {
            finalg = Integer.parseInt(enrlFinal.getText());
        }
        // do search action
        if (enrlSearchAction) {
            Object[][] result = db.searchEnrl(con, cid, sname, exam1, exam2, finalg);
            cleartable(enrlTable);
            addtoTable(enrlTable, result);
        }
        // do edit action
        else if (!enrlSearchAction && staffPermission){
            db.editEnrl(con, cid, sname, exam1, exam2, finalg);
            clearEnrlForm();
            enrlStudent.setEnabled(true);
            enrlCourse.setEnabled(true);
            enrlNew.setText("New");
            enrlNewAction = true;
            enrlSearch.setText("Search");
            enrlSearchAction = true;
            Object[][] allenrl = db.searchEnrl(con);
            cleartable(enrlTable);
            addtoTable(enrlTable,allenrl);
        }
    }//GEN-LAST:event_enrlSearchActionPerformed

    private void enrlClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrlClearActionPerformed
        cleartable(enrlTable);
        clearEnrlForm();
        enrlStudent.setEnabled(true);
        enrlCourse.setEnabled(true);
        enrlNew.setText("New");
        enrlNewAction = true;
        enrlSearch.setText("Search");
        enrlSearchAction = true;
        Database db = new Database();
        Object[][] allenrl = db.searchEnrl(con);
        addtoTable(enrlTable,allenrl);
    }//GEN-LAST:event_enrlClearActionPerformed

    // populate tables when tab selected
    private void facstaffTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_facstaffTabStateChanged
        JTabbedPane temp = (JTabbedPane) evt.getSource();
        int index = temp.getSelectedIndex();
        Database db = new Database();
        if (index == 0) {
            Object[][] allstu = db.searchStu(con);
            cleartable(stuTable);
            addtoTable(stuTable,allstu);
        }
        else if (index == 1) {
            Object[][] allfac = db.searchFac(con);
            cleartable(facTable);
            addtoTable(facTable,allfac);

        }
        else if (index == 2) {
            Object[][] allsta = db.searchSta(con);
            cleartable(staTable);
            addtoTable(staTable,allsta);
        }
        else if (index == 3) {
            Object[][] alldep = db.searchDep(con);
            cleartable(depTable);
            addtoTable(depTable,alldep);
        }
        else if (index == 4) {
            Object[][] allcor = db.searchCor(con);
            cleartable(corTable);
            addtoTable(corTable,allcor);
        }
        else if (index == 5) {
            Object[][] allenrl = db.searchEnrl(con);
            cleartable(enrlTable);
            addtoTable(enrlTable,allenrl);
        }
    }//GEN-LAST:event_facstaffTabStateChanged

    private void cleartable (JTable table) {
        table.clearSelection();
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        int rowcount = tableModel.getRowCount();
        for (int idx = 0; idx < rowcount; idx++) {
            tableModel.removeRow(0);
        }
    }

    public void addtoTable (JTable table, Object[][] data) {
        table.clearSelection();
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        if (data != null) {
            for (Object[] row : data) {
                tableModel.addRow(row);
            }
        }
    }

    public void clearStuForm () {
        stuID.setText("");
        stuName.setText("");
        stuMajor.setText("");
        stuLevel.setSelectedIndex(0);
        stuAge.setText("");
    }

    public void clearFacForm () {
        facID.setText("");
        facName.setText("");
        facDep.setSelectedItem("");
    }

    public void clearStaForm () {
        staID.setText("");
        staName.setText("");
        staDep.setSelectedItem("");
    }

    public void clearDepForm () {
        depID.setText("");
        depName.setText("");
    }

    public void clearCorForm () {
        corID.setText("");
        corName.setText("");
        corTime.setText("");
        corRoom.setText("");
        corInstructor.setSelectedItem("");
        corSize.setText("");
    }

    public void clearEnrlForm () {
        enrlCourse.setSelectedItem("");
        enrlStudent.setSelectedItem("");
        enrlExam1.setText("");
        enrlExam2.setText("");
        enrlFinal.setText("");
    }

    public Connection getConnection () {
        return this.con;
    }

    public void setConnection (Connection passedcon) {
        this.con = passedcon;
    }

    public boolean isStaffPermission() {
        return staffPermission;
    }

    public void setStaffPermission(boolean staffPermission) {
        this.staffPermission = staffPermission;
        if (staffPermission) {
            addStuTableListener();
            addFacTableListener();
            addStaTableListener();
            addDepTableListener();
            addCorTableListener();
            addEnrlTableListener();
        }
        else {
            disableNewButtons();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton corClear;
    private javax.swing.JTextField corID;
    private javax.swing.JLabel corIDLabel;
    private javax.swing.JComboBox corInstructor;
    private javax.swing.JLabel corInstructorLabel;
    private javax.swing.JTextField corName;
    private javax.swing.JLabel corNameLabel;
    private javax.swing.JButton corNew;
    private javax.swing.JTextField corRoom;
    private javax.swing.JLabel corRoomLabel;
    private javax.swing.JScrollPane corScroll;
    private javax.swing.JButton corSearch;
    private javax.swing.JTextField corSize;
    private javax.swing.JLabel corSizeLabel;
    private javax.swing.JTable corTable;
    private javax.swing.JTextField corTime;
    private javax.swing.JLabel corTimeLabel;
    private javax.swing.JPanel courseTab;
    private javax.swing.JButton depClear;
    private javax.swing.JTextField depID;
    private javax.swing.JLabel depIDLabel;
    private javax.swing.JTextField depName;
    private javax.swing.JLabel depNameLabel;
    private javax.swing.JButton depNew;
    private javax.swing.JScrollPane depScroll;
    private javax.swing.JButton depSearch;
    private javax.swing.JTable depTable;
    private javax.swing.JPanel deptTab;
    private javax.swing.JButton enrlClear;
    private javax.swing.JComboBox enrlCourse;
    private javax.swing.JLabel enrlCourseLabel;
    private javax.swing.JTextField enrlExam1;
    private javax.swing.JLabel enrlExam1Label;
    private javax.swing.JTextField enrlExam2;
    private javax.swing.JLabel enrlExam2Label;
    private javax.swing.JTextField enrlFinal;
    private javax.swing.JLabel enrlFinalLabel;
    private javax.swing.JButton enrlNew;
    private javax.swing.JScrollPane enrlScroll;
    private javax.swing.JButton enrlSearch;
    private javax.swing.JComboBox enrlStudent;
    private javax.swing.JLabel enrlStudentLabel;
    private javax.swing.JPanel enrlTab;
    private javax.swing.JTable enrlTable;
    private javax.swing.JButton facClear;
    private javax.swing.JComboBox facDep;
    private javax.swing.JLabel facDepLabel;
    private javax.swing.JTextField facID;
    private javax.swing.JLabel facIDLabel;
    private javax.swing.JTextField facName;
    private javax.swing.JLabel facNameLabel;
    private javax.swing.JButton facNew;
    private javax.swing.JScrollPane facScroll;
    private javax.swing.JButton facSearch;
    private javax.swing.JTable facTable;
    private javax.swing.JTabbedPane facstaffTab;
    private javax.swing.JPanel facultyTab;
    private javax.swing.JButton staClear;
    private javax.swing.JComboBox staDep;
    private javax.swing.JLabel staDepLabel;
    private javax.swing.JTextField staID;
    private javax.swing.JLabel staIDLabel;
    private javax.swing.JTextField staName;
    private javax.swing.JLabel staNameLabel;
    private javax.swing.JButton staNew;
    private javax.swing.JScrollPane staScroll;
    private javax.swing.JButton staSearch;
    private javax.swing.JTable staTable;
    private javax.swing.JPanel staffTab;
    private javax.swing.JTextField stuAge;
    private javax.swing.JLabel stuAgeLabel;
    private javax.swing.JButton stuClear;
    private javax.swing.JTextField stuID;
    private javax.swing.JLabel stuIDLabel;
    private javax.swing.JComboBox stuLevel;
    private javax.swing.JLabel stuLevelLabel;
    private javax.swing.JTextField stuMajor;
    private javax.swing.JLabel stuMajorLabel;
    private javax.swing.JTextField stuName;
    private javax.swing.JLabel stuNameLabel;
    private javax.swing.JButton stuNew;
    private javax.swing.JScrollPane stuScroll;
    private javax.swing.JButton stuSearch;
    private javax.swing.JTable stuTable;
    private javax.swing.JPanel studentTab;
    // End of variables declaration//GEN-END:variables
}
