
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anton
 */
public class FacultyStaff extends javax.swing.JFrame {

    private String DBUser;
    private String DBPw;
    /**
     * Creates new form MainWindow
     */
    public FacultyStaff() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            }
        catch (Exception e) {
            e.printStackTrace();
            }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        studentTab = new javax.swing.JPanel();
        stuNameLabel = new javax.swing.JLabel();
        stuName = new javax.swing.JTextField();
        stuMajorLabel = new javax.swing.JLabel();
        stuMajor = new javax.swing.JTextField();
        stuLevelLabel = new javax.swing.JLabel();
        stuLevel = new javax.swing.JComboBox();
        stuAgeLabel = new javax.swing.JLabel();
        stuAge1 = new javax.swing.JTextField();
        stuAge2 = new javax.swing.JTextField();
        stuSearch = new javax.swing.JButton();
        facultyTab = new javax.swing.JPanel();
        facNameLabel = new javax.swing.JLabel();
        facName = new javax.swing.JTextField();
        facDepLabel = new javax.swing.JLabel();
        facDep = new javax.swing.JTextField();
        facSearch = new javax.swing.JButton();
        staffTab = new javax.swing.JPanel();
        staNameLabel = new javax.swing.JLabel();
        staName = new javax.swing.JTextField();
        staDepLabel = new javax.swing.JLabel();
        staDep = new javax.swing.JTextField();
        staSearch = new javax.swing.JButton();
        deptTab = new javax.swing.JPanel();
        depNameLabel = new javax.swing.JLabel();
        depName = new javax.swing.JTextField();
        depSearch = new javax.swing.JButton();
        courseTab = new javax.swing.JPanel();
        corIDLabel = new javax.swing.JLabel();
        corID = new javax.swing.JTextField();
        corNameLabel = new javax.swing.JLabel();
        corName = new javax.swing.JTextField();
        corTimeLabel = new javax.swing.JLabel();
        corTime = new javax.swing.JTextField();
        corRoomLabel = new javax.swing.JLabel();
        corRoom = new javax.swing.JTextField();
        corSizeLabel = new javax.swing.JLabel();
        corSize = new javax.swing.JTextField();
        corSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stuNameLabel.setText("Name");

        stuMajorLabel.setText("Major");

        stuLevelLabel.setText("Level");

        stuLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Freshmen", "Sophomore", "Junior", "Senior", "Master", "PhD" }));

        stuAgeLabel.setText("Age");

        stuSearch.setText("Search");
        stuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentTabLayout = new javax.swing.GroupLayout(studentTab);
        studentTab.setLayout(studentTabLayout);
        studentTabLayout.setHorizontalGroup(
            studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTabLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentTabLayout.createSequentialGroup()
                        .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuAgeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stuNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stuMajorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stuLevelLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stuMajor)
                            .addComponent(stuLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentTabLayout.createSequentialGroup()
                                .addComponent(stuAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(stuAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stuSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentTabLayout.setVerticalGroup(
            studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuNameLabel)
                    .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuMajorLabel)
                    .addComponent(stuMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuLevelLabel)
                    .addComponent(stuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuAgeLabel)
                    .addComponent(stuAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stuAge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(stuSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Students", studentTab);

        facNameLabel.setText("Name");

        facDepLabel.setText("Department");

        facSearch.setText("Search");
        facSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facultyTabLayout = new javax.swing.GroupLayout(facultyTab);
        facultyTab.setLayout(facultyTabLayout);
        facultyTabLayout.setHorizontalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facSearch)
                    .addGroup(facultyTabLayout.createSequentialGroup()
                        .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(facDepLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(facDep)
                            .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        facultyTabLayout.setVerticalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facNameLabel)
                    .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facDepLabel)
                    .addComponent(facDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(facSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Faculty", facultyTab);

        staNameLabel.setText("Name");

        staDepLabel.setText("Department");

        staSearch.setText("Search");
        staSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffTabLayout = new javax.swing.GroupLayout(staffTab);
        staffTab.setLayout(staffTabLayout);
        staffTabLayout.setHorizontalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staSearch)
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(staDepLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staDep)
                            .addComponent(staName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        staffTabLayout.setVerticalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staNameLabel)
                    .addComponent(staName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staDepLabel)
                    .addComponent(staDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(staSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Staff", staffTab);

        depNameLabel.setText("Name");

        depSearch.setText("Search");
        depSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deptTabLayout = new javax.swing.GroupLayout(deptTab);
        deptTab.setLayout(deptTabLayout);
        deptTabLayout.setHorizontalGroup(
            deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(depSearch)
                    .addGroup(deptTabLayout.createSequentialGroup()
                        .addComponent(depNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deptTabLayout.setVerticalGroup(
            deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depNameLabel)
                    .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(depSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Departments", deptTab);

        corIDLabel.setText("ID");

        corNameLabel.setText("Name");

        corTimeLabel.setText("Time");

        corRoomLabel.setText("Room");

        corSizeLabel.setText("Size Limit");

        corSearch.setText("Search");
        corSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout courseTabLayout = new javax.swing.GroupLayout(courseTab);
        courseTab.setLayout(courseTabLayout);
        courseTabLayout.setHorizontalGroup(
            courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseTabLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(corSearch)
                    .addGroup(courseTabLayout.createSequentialGroup()
                        .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(corNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(corSizeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(corTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(corRoomLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(corSize, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(corRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(corName)
                            .addComponent(corID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(corTime))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        courseTabLayout.setVerticalGroup(
            courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corIDLabel)
                    .addComponent(corID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corNameLabel)
                    .addComponent(corName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corTimeLabel)
                    .addComponent(corTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corRoomLabel)
                    .addComponent(corRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corSizeLabel)
                    .addComponent(corSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(corSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Courses", courseTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuSearchActionPerformed
        Results popup = new Results();
        popup.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        String[] cols = {"Test"};
        Object[][] rows = {{"Test"}};
        popup.setCols(cols);
        popup.setRows(rows);
        popup.populateTable();
        popup.setVisible(true);
    }//GEN-LAST:event_stuSearchActionPerformed

    private void facSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facSearchActionPerformed

    private void depSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depSearchActionPerformed

    private void staSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staSearchActionPerformed

    private void corSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corSearchActionPerformed
   
    public String getDBUser () {
        return this.DBUser;
    }
    
    public void setDBUser (String value) {
        this.DBUser = value;
    }
    
    public String getDBPw () {
        return this.DBPw;
    }
    
    public void setDBPw (String value) {
        this.DBPw = value;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField corID;
    private javax.swing.JLabel corIDLabel;
    private javax.swing.JTextField corName;
    private javax.swing.JLabel corNameLabel;
    private javax.swing.JTextField corRoom;
    private javax.swing.JLabel corRoomLabel;
    private javax.swing.JButton corSearch;
    private javax.swing.JTextField corSize;
    private javax.swing.JLabel corSizeLabel;
    private javax.swing.JTextField corTime;
    private javax.swing.JLabel corTimeLabel;
    private javax.swing.JPanel courseTab;
    private javax.swing.JTextField depName;
    private javax.swing.JLabel depNameLabel;
    private javax.swing.JButton depSearch;
    private javax.swing.JPanel deptTab;
    private javax.swing.JTextField facDep;
    private javax.swing.JLabel facDepLabel;
    private javax.swing.JTextField facName;
    private javax.swing.JLabel facNameLabel;
    private javax.swing.JButton facSearch;
    private javax.swing.JPanel facultyTab;
    private javax.swing.JTextField staDep;
    private javax.swing.JLabel staDepLabel;
    private javax.swing.JTextField staName;
    private javax.swing.JLabel staNameLabel;
    private javax.swing.JButton staSearch;
    private javax.swing.JPanel staffTab;
    private javax.swing.JTextField stuAge1;
    private javax.swing.JTextField stuAge2;
    private javax.swing.JLabel stuAgeLabel;
    private javax.swing.JComboBox stuLevel;
    private javax.swing.JLabel stuLevelLabel;
    private javax.swing.JTextField stuMajor;
    private javax.swing.JLabel stuMajorLabel;
    private javax.swing.JTextField stuName;
    private javax.swing.JLabel stuNameLabel;
    private javax.swing.JButton stuSearch;
    private javax.swing.JPanel studentTab;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
