
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anton
 */
public class FacultyStaff extends javax.swing.JFrame {

    private Connection con;
    /**
     * Creates new form
     */
    public FacultyStaff() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            }
        catch (Exception e) {
            e.printStackTrace();
            }
        initComponents();
    }

    public FacultyStaff(Connection passedcon) {
        setConnection(passedcon);
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facstaffTab = new javax.swing.JTabbedPane();
        studentTab = new javax.swing.JPanel();
        studIDLabel = new javax.swing.JLabel();
        studID = new javax.swing.JTextField();
        stuNameLabel = new javax.swing.JLabel();
        stuName = new javax.swing.JTextField();
        stuMajorLabel = new javax.swing.JLabel();
        stuMajor = new javax.swing.JTextField();
        stuLevelLabel = new javax.swing.JLabel();
        stuLevel = new javax.swing.JComboBox();
        stuAgeLabel = new javax.swing.JLabel();
        stuAge = new javax.swing.JTextField();
        stuSearch = new javax.swing.JButton();
        stuClear = new javax.swing.JButton();
        stuScroll = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        facultyTab = new javax.swing.JPanel();
        facIDLabel = new javax.swing.JLabel();
        facID = new javax.swing.JTextField();
        facNameLabel = new javax.swing.JLabel();
        facName = new javax.swing.JTextField();
        facDepLabel = new javax.swing.JLabel();
        facDep = new javax.swing.JTextField();
        facSearch = new javax.swing.JButton();
        facClear = new javax.swing.JButton();
        facScroll = new javax.swing.JScrollPane();
        facTable = new javax.swing.JTable();
        staffTab = new javax.swing.JPanel();
        staIDLabel = new javax.swing.JLabel();
        staID = new javax.swing.JTextField();
        staNameLabel = new javax.swing.JLabel();
        staName = new javax.swing.JTextField();
        staDepLabel = new javax.swing.JLabel();
        staDep = new javax.swing.JTextField();
        staSearch = new javax.swing.JButton();
        staClear = new javax.swing.JButton();
        staScroll = new javax.swing.JScrollPane();
        staTable = new javax.swing.JTable();
        deptTab = new javax.swing.JPanel();
        depIDLabel = new javax.swing.JLabel();
        depID = new javax.swing.JTextField();
        depNameLabel = new javax.swing.JLabel();
        depName = new javax.swing.JTextField();
        depSearch = new javax.swing.JButton();
        depClear = new javax.swing.JButton();
        depScroll = new javax.swing.JScrollPane();
        depTable = new javax.swing.JTable();
        courseTab = new javax.swing.JPanel();
        corIDLabel = new javax.swing.JLabel();
        corID = new javax.swing.JTextField();
        corNameLabel = new javax.swing.JLabel();
        corName = new javax.swing.JTextField();
        corTimeLabel = new javax.swing.JLabel();
        corTime = new javax.swing.JTextField();
        corRoomLabel = new javax.swing.JLabel();
        corRoom = new javax.swing.JTextField();
        corInstructorLabel = new javax.swing.JLabel();
        corInstructor = new javax.swing.JTextField();
        corSizeLabel = new javax.swing.JLabel();
        corSize = new javax.swing.JTextField();
        corSearch = new javax.swing.JButton();
        corClear = new javax.swing.JButton();
        corScroll = new javax.swing.JScrollPane();
        corTable = new javax.swing.JTable();
        enrlTab = new javax.swing.JPanel();
        enrlCourseLabel = new javax.swing.JLabel();
        enrlCourse = new javax.swing.JTextField();
        enrlStudentLabel = new javax.swing.JLabel();
        enrlStudent = new javax.swing.JTextField();
        enrlExam1Label = new javax.swing.JLabel();
        enrlExam1 = new javax.swing.JTextField();
        enrlExam2Label = new javax.swing.JLabel();
        enrlExam2 = new javax.swing.JTextField();
        enrlFinalLabel = new javax.swing.JLabel();
        enrlFinal = new javax.swing.JTextField();
        enrlSearch = new javax.swing.JButton();
        enrlScroll = new javax.swing.JScrollPane();
        enrlTable = new javax.swing.JTable();
        enrlClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facstaffTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                facstaffTabStateChanged(evt);
            }
        });

        studentTab.setPreferredSize(new java.awt.Dimension(700, 500));

        studIDLabel.setText("ID");

        stuNameLabel.setText("Name");

        stuMajorLabel.setText("Major");

        stuLevelLabel.setText("Level");

        stuLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","Freshman", "Sophomore", "Junior", "Senior", "Master", "PhD" }));

        stuAgeLabel.setText("Age");

        stuSearch.setText("Search");
        stuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuSearchActionPerformed(evt);
            }
        });

        stuClear.setText("Clear");
        stuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuClearActionPerformed(evt);
            }
        });

        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Major", "Level", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stuScroll.setViewportView(stuTable);

        javax.swing.GroupLayout studentTabLayout = new javax.swing.GroupLayout(studentTab);
        studentTab.setLayout(studentTabLayout);
        studentTabLayout.setHorizontalGroup(
            studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stuScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(studentTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentTabLayout.createSequentialGroup()
                        .addComponent(stuSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stuClear))
                    .addGroup(studentTabLayout.createSequentialGroup()
                        .addComponent(stuAgeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stuAge, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentTabLayout.createSequentialGroup()
                        .addComponent(studIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentTabLayout.createSequentialGroup()
                        .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stuNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stuMajorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stuLevelLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stuMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentTabLayout.setVerticalGroup(
            studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studIDLabel)
                    .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuNameLabel)
                    .addComponent(stuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuMajorLabel)
                    .addComponent(stuMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuLevelLabel)
                    .addComponent(stuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuAgeLabel)
                    .addComponent(stuAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuClear)
                    .addComponent(stuSearch))
                .addGap(18, 18, 18)
                .addComponent(stuScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Students", studentTab);

        facultyTab.setPreferredSize(new java.awt.Dimension(700, 50));

        facIDLabel.setText("ID");

        facNameLabel.setText("Name");

        facDepLabel.setText("Department");

        facSearch.setText("Search");
        facSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facSearchActionPerformed(evt);
            }
        });

        facClear.setText("Clear");
        facClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facClearActionPerformed(evt);
            }
        });

        facTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facScroll.setViewportView(facTable);

        javax.swing.GroupLayout facultyTabLayout = new javax.swing.GroupLayout(facultyTab);
        facultyTab.setLayout(facultyTabLayout);
        facultyTabLayout.setHorizontalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(facultyTabLayout.createSequentialGroup()
                        .addComponent(facSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facClear))
                    .addGroup(facultyTabLayout.createSequentialGroup()
                        .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(facDepLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(facDep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(facultyTabLayout.createSequentialGroup()
                        .addComponent(facIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        facultyTabLayout.setVerticalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facIDLabel)
                    .addComponent(facID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facNameLabel)
                    .addComponent(facName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facDepLabel)
                    .addComponent(facDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facClear)
                    .addComponent(facSearch))
                .addGap(18, 18, 18)
                .addComponent(facScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Faculty", facultyTab);

        staffTab.setPreferredSize(new java.awt.Dimension(700, 500));

        staIDLabel.setText("ID");

        staNameLabel.setText("Name");

        staDepLabel.setText("Department");

        staSearch.setText("Search");
        staSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staSearchActionPerformed(evt);
            }
        });

        staClear.setText("Clear");
        staClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staClearActionPerformed(evt);
            }
        });

        staTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staScroll.setViewportView(staTable);

        javax.swing.GroupLayout staffTabLayout = new javax.swing.GroupLayout(staffTab);
        staffTab.setLayout(staffTabLayout);
        staffTabLayout.setHorizontalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addComponent(staSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staClear))
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(staDepLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staDep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addComponent(staIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffTabLayout.setVerticalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staIDLabel)
                    .addComponent(staID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staNameLabel)
                    .addComponent(staName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staDepLabel)
                    .addComponent(staDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staClear)
                    .addComponent(staSearch))
                .addGap(18, 18, 18)
                .addComponent(staScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Staff", staffTab);

        deptTab.setPreferredSize(new java.awt.Dimension(700, 500));

        depIDLabel.setText("ID");

        depNameLabel.setText("Name");

        depSearch.setText("Search");
        depSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depSearchActionPerformed(evt);
            }
        });

        depClear.setText("Clear");
        depClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depClearActionPerformed(evt);
            }
        });

        depTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        depScroll.setViewportView(depTable);

        javax.swing.GroupLayout deptTabLayout = new javax.swing.GroupLayout(deptTab);
        deptTab.setLayout(deptTabLayout);
        deptTabLayout.setHorizontalGroup(
            deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(deptTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deptTabLayout.createSequentialGroup()
                        .addComponent(depIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deptTabLayout.createSequentialGroup()
                        .addComponent(depNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deptTabLayout.createSequentialGroup()
                        .addComponent(depSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deptTabLayout.setVerticalGroup(
            deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depIDLabel)
                    .addComponent(depID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depNameLabel)
                    .addComponent(depName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depSearch)
                    .addComponent(depClear))
                .addGap(18, 18, 18)
                .addComponent(depScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Departments", deptTab);

        courseTab.setPreferredSize(new java.awt.Dimension(700, 500));

        corIDLabel.setText("ID");

        corNameLabel.setText("Name");

        corTimeLabel.setText("Time");

        corRoomLabel.setText("Location");

        corInstructorLabel.setText("Instructor");

        corSizeLabel.setText("Size Limit");

        corSearch.setText("Search");
        corSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corSearchActionPerformed(evt);
            }
        });

        corClear.setText("Clear");
        corClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corClearActionPerformed(evt);
            }
        });

        corTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Time", "Location", "Instructor", "Size Limit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        corScroll.setViewportView(corTable);

        javax.swing.GroupLayout courseTabLayout = new javax.swing.GroupLayout(courseTab);
        courseTab.setLayout(courseTabLayout);
        courseTabLayout.setHorizontalGroup(
            courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(courseTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corRoomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corInstructorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corSizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corSize, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseTabLayout.createSequentialGroup()
                        .addComponent(corSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        courseTabLayout.setVerticalGroup(
            courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corIDLabel)
                    .addComponent(corID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corNameLabel)
                    .addComponent(corName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corTimeLabel)
                    .addComponent(corTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corRoomLabel)
                    .addComponent(corRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corInstructorLabel)
                    .addComponent(corInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corSizeLabel)
                    .addComponent(corSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(courseTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corClear)
                    .addComponent(corSearch))
                .addGap(18, 18, 18)
                .addComponent(corScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Courses", courseTab);

        enrlTab.setPreferredSize(new java.awt.Dimension(700, 500));

        enrlCourseLabel.setText("Course");

        enrlStudentLabel.setText("Student");

        enrlExam1Label.setText("Exam 1");

        enrlExam2Label.setText("Exam 2");

        enrlFinalLabel.setText("Final");

        enrlSearch.setText("Search");
        enrlSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrlSearchActionPerformed(evt);
            }
        });

        enrlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Student", "Exam 1", "Exam 2", "Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrlScroll.setViewportView(enrlTable);

        enrlClear.setText("Clear");
        enrlClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrlClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enrlTabLayout = new javax.swing.GroupLayout(enrlTab);
        enrlTab.setLayout(enrlTabLayout);
        enrlTabLayout.setHorizontalGroup(
            enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrlTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enrlTabLayout.createSequentialGroup()
                        .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enrlCourseLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlStudentLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlFinalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlExam1Label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enrlExam2Label, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enrlFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrlExam2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrlCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrlExam1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enrlTabLayout.createSequentialGroup()
                        .addComponent(enrlSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enrlClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(enrlScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        enrlTabLayout.setVerticalGroup(
            enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrlTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlCourseLabel)
                    .addComponent(enrlCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlStudentLabel)
                    .addComponent(enrlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlExam1Label)
                    .addComponent(enrlExam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlExam2Label)
                    .addComponent(enrlExam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlFinalLabel)
                    .addComponent(enrlFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(enrlTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrlSearch)
                    .addComponent(enrlClear))
                .addGap(18, 18, 18)
                .addComponent(enrlScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        facstaffTab.addTab("Enrollment", enrlTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(facstaffTab)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(facstaffTab)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuSearchActionPerformed
//        Results popup = new Results();
//        popup.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
//        String[] cols = {"Test"};
//        Object[][] rows = {{"Test"}};
//        popup.setCols(cols);
//        popup.setRows(rows);
//        popup.populateTable();
//        popup.setVisible(true);
        Database db = new Database();
        Integer sid = -1;
        String sname = "-1";
        String major = "-1";
        String s_level = "-1";
        Integer age = -1;
        if (!studID.getText().isEmpty()) {
            sid = Integer.parseInt(studID.getText());
        }
        if (!stuName.getText().isEmpty()) {
            sname = stuName.getText();
        }
        if (!stuMajor.getText().isEmpty()) {
            major = stuMajor.getText();
        }
        if (!String.valueOf(stuLevel.getSelectedItem()).isEmpty()) {
            s_level = String.valueOf(stuLevel.getSelectedItem()).toLowerCase();
        }
        if (!stuAge.getText().isEmpty()) {
            age = Integer.parseInt(stuAge.getText());
        }
        Object[][] result = db.searchStu(con,sid,sname,major,s_level,age);
        cleartable(stuTable);
        addtoTable(stuTable,result);
    }//GEN-LAST:event_stuSearchActionPerformed

    private void facSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facSearchActionPerformed

    private void depSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depSearchActionPerformed

    private void staSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staSearchActionPerformed

    private void corSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corSearchActionPerformed

    private void enrlSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrlSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrlSearchActionPerformed

    private void enrlClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrlClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrlClearActionPerformed

    private void corClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corClearActionPerformed

    private void depClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depClearActionPerformed

    private void staClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staClearActionPerformed

    private void facClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facClearActionPerformed

    private void stuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuClearActionPerformed
        cleartable(stuTable);
        studID.setText("");
        stuName.setText("");
        stuMajor.setText("");
        stuLevel.setSelectedIndex(0);
        stuAge.setText("");
        Database db = new Database();
        Object[][] allstu = db.searchStu(con);
        addtoTable(stuTable,allstu);

    }//GEN-LAST:event_stuClearActionPerformed

    private void facstaffTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_facstaffTabStateChanged
        JTabbedPane temp = (JTabbedPane) evt.getSource();
        int index = temp.getSelectedIndex();
        Database db = new Database();
        if (index == 0) {
            Object[][] allstu = db.searchStu(con);
            cleartable(stuTable);
            addtoTable(stuTable,allstu);
        }
    }//GEN-LAST:event_facstaffTabStateChanged

    private void cleartable (JTable table) {
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        int rowcount = tableModel.getRowCount();
        for (int idx = 0; idx < rowcount; idx++) {
            tableModel.removeRow(0);
        }
    }

    public void addtoTable (JTable table, Object[][] data) {
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        if (data != null) {
            for (Object[] row : data) {
                tableModel.addRow(row);
            }
        }
    }

    public Connection getConnection () {
        return this.con;
    }

    public void setConnection (Connection passedcon) {
        this.con = passedcon;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton corClear;
    private javax.swing.JTextField corID;
    private javax.swing.JLabel corIDLabel;
    private javax.swing.JTextField corInstructor;
    private javax.swing.JLabel corInstructorLabel;
    private javax.swing.JTextField corName;
    private javax.swing.JLabel corNameLabel;
    private javax.swing.JTextField corRoom;
    private javax.swing.JLabel corRoomLabel;
    private javax.swing.JScrollPane corScroll;
    private javax.swing.JButton corSearch;
    private javax.swing.JTextField corSize;
    private javax.swing.JLabel corSizeLabel;
    private javax.swing.JTable corTable;
    private javax.swing.JTextField corTime;
    private javax.swing.JLabel corTimeLabel;
    private javax.swing.JPanel courseTab;
    private javax.swing.JButton depClear;
    private javax.swing.JTextField depID;
    private javax.swing.JLabel depIDLabel;
    private javax.swing.JTextField depName;
    private javax.swing.JLabel depNameLabel;
    private javax.swing.JScrollPane depScroll;
    private javax.swing.JButton depSearch;
    private javax.swing.JTable depTable;
    private javax.swing.JPanel deptTab;
    private javax.swing.JButton enrlClear;
    private javax.swing.JTextField enrlCourse;
    private javax.swing.JLabel enrlCourseLabel;
    private javax.swing.JTextField enrlExam1;
    private javax.swing.JLabel enrlExam1Label;
    private javax.swing.JTextField enrlExam2;
    private javax.swing.JLabel enrlExam2Label;
    private javax.swing.JTextField enrlFinal;
    private javax.swing.JLabel enrlFinalLabel;
    private javax.swing.JScrollPane enrlScroll;
    private javax.swing.JButton enrlSearch;
    private javax.swing.JTextField enrlStudent;
    private javax.swing.JLabel enrlStudentLabel;
    private javax.swing.JPanel enrlTab;
    private javax.swing.JTable enrlTable;
    private javax.swing.JButton facClear;
    private javax.swing.JTextField facDep;
    private javax.swing.JLabel facDepLabel;
    private javax.swing.JTextField facID;
    private javax.swing.JLabel facIDLabel;
    private javax.swing.JTextField facName;
    private javax.swing.JLabel facNameLabel;
    private javax.swing.JScrollPane facScroll;
    private javax.swing.JButton facSearch;
    private javax.swing.JTable facTable;
    private javax.swing.JTabbedPane facstaffTab;
    private javax.swing.JPanel facultyTab;
    private javax.swing.JButton staClear;
    private javax.swing.JTextField staDep;
    private javax.swing.JLabel staDepLabel;
    private javax.swing.JTextField staID;
    private javax.swing.JLabel staIDLabel;
    private javax.swing.JTextField staName;
    private javax.swing.JLabel staNameLabel;
    private javax.swing.JScrollPane staScroll;
    private javax.swing.JButton staSearch;
    private javax.swing.JTable staTable;
    private javax.swing.JPanel staffTab;
    private javax.swing.JTextField stuAge;
    private javax.swing.JLabel stuAgeLabel;
    private javax.swing.JButton stuClear;
    private javax.swing.JComboBox stuLevel;
    private javax.swing.JLabel stuLevelLabel;
    private javax.swing.JTextField stuMajor;
    private javax.swing.JLabel stuMajorLabel;
    private javax.swing.JTextField stuName;
    private javax.swing.JLabel stuNameLabel;
    private javax.swing.JScrollPane stuScroll;
    private javax.swing.JButton stuSearch;
    private javax.swing.JTable stuTable;
    private javax.swing.JTextField studID;
    private javax.swing.JLabel studIDLabel;
    private javax.swing.JPanel studentTab;
    // End of variables declaration//GEN-END:variables
}
